apiVersion: v1
kind: Service
metadata:
  name: ml-cicd-predictor
  labels:
    app: ml-cicd-predictor
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http-direct
  selector:
    app: ml-cicd-predictor
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: ml-cicd-predictor-headless
  labels:
    app: ml-cicd-predictor
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: ml-cicd-predictor
